#!/usr/bin/env zsh

# Rust executor that mixes in different CLI tools to have a matching experiance compared to other languages.
# Uses cargo-run-bin to execute binaries from Cargo.toml. https://crates.io/crates/cargo-run-bin
# Uses cargo-cmd to execute scripts from Cargo.toml. https://crates.io/crates/cargo-cmd
#
# Usage:
#   rur --help (cargo --help)
#   rur my-script.rs
#   rur my-binary
#   rur my-cargo-script

set -e

function walkuptree() {
  local DIR=$(pwd)
  while [ ! -z "$DIR" ] && [ ! -f "$DIR/$1" ]; do
    DIR="${DIR%\/*}"
  done

  echo "$DIR/$1"
}

CARGOTOML_PATH=$(walkuptree Cargo.toml)

rustcmd=""
if [[ "$1" == *.rs ]]; then
  rustcmd="rustc $@"
elif (cat $CARGOTOML_PATH | sed -n '/package.metadata.commands/,/^\[/p' | grep ' = ' | awk '{print $1}' || echo '') | grep -q ^"$1"$; then
  rustcmd="cargo cmd $@"
elif (cargo bin --list-binaries | grep -q ^"$1"$); then
  rustcmd="cargo bin $@"
else
  rustcmd="cargo"
fi

# Support passing in stdin.
if [ ! -t 0 ]; then
  rustcmd="cat - | $rustcmd"
fi

eval "$rustcmd"
